apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: iothub_invoke
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    secretKeyRef:
        name: urls
        key:  iothub_twinurl